default_platform(:ios)

api_key = app_store_connect_api_key(
  key_id: "3Q9U495BMY",
  issuer_id: "69a6de96-d63c-47e3-e053-5b8c7c11a4d1",
  key_filepath: "AuthKey_3Q9U495BMY.p8",
  duration: 1200, 
  in_house: false, 
)

# Determine bundle identifier based on APP_VARIANT
bundle_identifier = ENV.fetch('APP_VARIANT', '') == 'production' ? 
  "de.democracy-deutschland.clientapp" : 
  "de.democracy-deutschland.clientapp.internal"

# Determine the app variant name for XCode project references
variant = ENV.fetch('APP_VARIANT', '') == 'production' ? "" : "Internal"

platform :ios do
  force_value = ENV["MATCH_FORCE"] == "true"

  lane :next_build_number do
    build_number_internal = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "de.democracy-deutschland.clientapp.internal"
    ).to_i
    build_number_production = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "de.democracy-deutschland.clientapp"
    ).to_i
    build_number = [build_number_internal, build_number_production].max + 1
    UI.message "Next build number: #{build_number}"
    build_number
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "development",
      readonly: false,
      force: force_value
    )
    sync_code_signing(
      type: "appstore",
      readonly: false,
      force: force_value
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :deploy do
    setup_ci if ENV['CI']

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV['FASTLANE_TEAM_ID'],
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AppStore #{bundle_identifier}",
      path: "../../ios/DEMOCRACY#{variant}.xcodeproj"
    )
    
    generate_new_certificates  
    
    update_info_plist(
      plist_path: "DEMOCRACY#{variant}/Info.plist",
      xcodeproj: "../../ios/DEMOCRACY#{variant}.xcodeproj",
      block: lambda { |plist|
        plist["ITSAppUsesNonExemptEncryption"] = false
      }
    )

    build_number = next_build_number

    increment_build_number(
      xcodeproj: "../../ios/DEMOCRACY#{variant}.xcodeproj",
      build_number: build_number
    )

    build_app(
      workspace: "../../ios/DEMOCRACY#{variant}.xcworkspace",
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
