# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :setup_signing do
  setup_travis

  match(type: 'appstore')
end

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :test_sign do
    setup_travis
    sync_code_signing(
      readonly: true,
      type: 'development',
      verbose: true
    )
    end

  lane :beta do
    setup_travis
    sync_code_signing(
      readonly: true
    )
    increment_build_number(xcodeproj: "democracyclient.xcodeproj")
    build_app(scheme: "democracyclient-prod")
    upload_to_testflight(
      groups: '-g "Developer"'
    )
  end
end
