# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    # build_android_app(
    #   task: "test",
    #   build_type: "Release"
    # )
  end

  desc "Validate"
  lane :validate do
    supply(
      validate_only: true
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :alpha do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: 'alpha',
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
